F18 banner
cmugpi/cmugpi.github.io pull request #36
Opened 2019-08-29 15:17 UTC by J3698

Add a banner to redirect to current GPI website.

2019-08-29 15:30 UTC, jbrown215 requested changes

2019-08-29 15:30 UTC, jbrown215 commented on _includes/header.html
> +      <div class="banner red sixteen wide center aligned computer only column" style="padding-bottom: 0">
It looks like you have the same banner here twice. Is one supposed to link back to a previous semester?

2019-08-29 15:30 UTC, jbrown215 commented on _sass/_overrides.scss
> +.ui.grid>.column:not(.row) {
These two snippets look identical. I don't think that was intentional-- you also happen to have two commits in your stack with the same title and same changes. You may have accidentally applied a patch twice?

2019-08-30 20:02 UTC, dhashe approved these changes
lgtm

2019-08-31 19:21 UTC, merged